### ISSUE TITLE
Can't find requirements.txt

### ISSUE THREAD

**Issue by Niubbo75** [scs-labrat/mxflex#1]
Hi, after cloning your repo I can't find requirements.txt and I can't clone it with your command:
git clone https://github.com/yourusername/mxflex.git also if I write my github user name, I can clone it only with yours, maybe a typo?
Can you please provide the required file and fix your README file?
Best regards,
Alessandro

**Comment by scs-labrat** [comment]
Yeah no worries.  I've had a few thing on so haven't had a chance to revisit it..  Will get it sorted asap

**Comment by Niubbo75** [comment]
> Yeah no worries. I've had a few thing on so haven't had a chance to revisit it.. Will get it sorted asap

Ok, thanks for your reply!
I'll wait till you find the time to do it, thanks!

**Comment by scs-labrat** [comment]
That's all done mate..   You might need the geminiAI library as well.  I think one of the offensive tools I added might need it

**Comment by scs-labrat** [comment]
Peace
